# Generated by Django 5.2.7 on 2025-11-09 09:50

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("data", "0005_inventoryuploadrecord_stockalert_stockmovement"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerChurnScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recency_score", models.PositiveSmallIntegerField()),
                ("frequency_score", models.PositiveSmallIntegerField()),
                ("monetary_score", models.PositiveSmallIntegerField()),
                ("rfm_score", models.PositiveSmallIntegerField()),
                ("rfm_segment", models.CharField(max_length=32)),
                (
                    "churn_risk_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("churn_risk_level", models.CharField(max_length=16)),
                ("risk_reason", models.CharField(max_length=255)),
                ("purchase_count", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "avg_purchase_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("days_since_purchase", models.PositiveIntegerField(default=0)),
                ("last_purchase", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_scores",
                        to="accounts.business",
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="churn_score",
                        to="data.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer churn score",
                "verbose_name_plural": "Customer churn scores",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "churn_risk_level"],
                        name="churn_custo_busines_fcb671_idx",
                    ),
                    models.Index(
                        fields=["business", "rfm_segment"],
                        name="churn_custo_busines_c47790_idx",
                    ),
                ],
            },
        ),
    ]
