# Generated by Django 5.2.7 on 2025-11-06 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_point",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="csv_import_hash",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("business", "csv_import_hash")},
        ),
        migrations.CreateModel(
            name="FailedJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("row_data", models.JSONField()),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_jobs",
                        to="accounts.business",
                    ),
                ),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failed_rows",
                        to="data.fileuploadrecord",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Failed Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
