# Generated by Django 5.2.7 on 2025-11-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("data", "0003_receiptuploadrecord"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["business", "date"], name="data_transa_busines_40d778_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["business", "created_at"], name="data_transa_busines_a9b783_idx"
            ),
        ),
    ]
