from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register the ViewSets
router = DefaultRouter()
router.register(r'transactions', views.TransactionViewSet, basename='transaction')
router.register(r'inventory/products', views.ProductListViewSet, basename='product-list')
router.register(r'inventory/movements', views.StockMovementViewSet, basename='stock-movement')
router.register(r'inventory/alerts', views.StockAlertViewSet, basename='stock-alert')

urlpatterns = [
    # CSV upload endpoints
    path('upload-csv/', views.upload_csv, name='upload_csv'),
    path('upload-csv/<uuid:file_id>/', views.get_upload_status, name='get_upload_status'),

    # Receipt upload endpoints
    path('upload-receipt/', views.upload_receipt, name='upload_receipt'),
    path('upload-receipt/<uuid:image_id>/', views.get_receipt_status, name='get_receipt_status'),

    # Receipt preview and action endpoints
    path('receipts/<uuid:image_id>/', views.get_receipt_preview, name='get_receipt_preview'),
    path('receipts/<uuid:image_id>/confirm/', views.confirm_receipt, name='confirm_receipt'),
    path('receipts/<uuid:image_id>/reject/', views.reject_receipt, name='reject_receipt'),

    # Admin endpoints
    path('admin/failed-jobs/', views.list_failed_jobs, name='list_failed_jobs'),
    path('admin/failed-jobs/<uuid:job_id>/retry/', views.retry_failed_job, name='retry_failed_job'),
    path('admin/upload-status/', views.upload_status_monitoring, name='upload_status_monitoring'),

    # Inventory management endpoints
    path('inventory/upload-stock/', views.upload_inventory_csv, name='upload_inventory_csv'),
    path('inventory/upload-stock/<uuid:record_id>/', views.get_inventory_upload_status, name='get_inventory_upload_status'),
    path('inventory/transactions/', views.record_sale, name='record_sale'),
    path('inventory/report/', views.get_inventory_report, name='get_inventory_report'),

    # ViewSet routes (auto-generated by router)
    path('', include(router.urls)),
]
